-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 22:13:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sample` ;

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sample` ;

-- -----------------------------------------------------
-- Table `sample`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`files` ;

CREATE TABLE IF NOT EXISTS `sample`.`files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date of the last updaste as a file version',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Files used in tests';


-- -----------------------------------------------------
-- Table `sample`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `sample`.`user_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(45) NOT NULL DEFAULT 'tester' COMMENT 'Useer role: : su, admin, tester',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_role_UNIQUE` (`user_role` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Users roles to manage access';


-- -----------------------------------------------------
-- Table `sample`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`users` ;

CREATE TABLE IF NOT EXISTS `sample`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'User name',
  `id_role` INT UNSIGNED NOT NULL COMMENT 'User role',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_role_idx_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_role_idx`
    FOREIGN KEY (`id_role`)
    REFERENCES `sample`.`user_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Users list';


-- -----------------------------------------------------
-- Table `sample`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`notifications` ;

CREATE TABLE IF NOT EXISTS `sample`.`notifications` (
  `id_user` INT UNSIGNED NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  INDEX `fk_to_user_key_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_to_user_key`
    FOREIGN KEY (`id_user`)
    REFERENCES `sample`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Notifications to users';


-- -----------------------------------------------------
-- Table `sample`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`projects` ;

CREATE TABLE IF NOT EXISTS `sample`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Test projects as categories of tests';


-- -----------------------------------------------------
-- Table `sample`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`schedules` ;

CREATE TABLE IF NOT EXISTS `sample`.`schedules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Schedule alias',
  `start_at` TIME NOT NULL,
  `stop_at` TIME NULL DEFAULT NULL COMMENT 'Optional stop time as a duration limit',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Schedules to process tasks';


-- -----------------------------------------------------
-- Table `sample`.`units_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`units_types` ;

CREATE TABLE IF NOT EXISTS `sample`.`units_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_type` VARCHAR(45) NOT NULL COMMENT 'Unit type as a varchar',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_type_UNIQUE` (`u_type` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tested unit types to direct tests to';


-- -----------------------------------------------------
-- Table `sample`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`tests` ;

CREATE TABLE IF NOT EXISTS `sample`.`tests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_project` INT UNSIGNED NOT NULL COMMENT 'Test project',
  `name` VARCHAR(45) NOT NULL COMMENT 'Unique project name',
  `id_u_type` INT UNSIGNED NOT NULL COMMENT 'Tested unit type',
  `id_file` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Linked to a test file',
  `id_author` INT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `id_project`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_id_u_type_idx` (`id_u_type` ASC) VISIBLE,
  INDEX `fk_project_idx` (`id_project` ASC) VISIBLE,
  INDEX `fk_id_file_idx` (`id_file` ASC) VISIBLE,
  INDEX `fk_author_key_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `fk_author_key`
    FOREIGN KEY (`id_author`)
    REFERENCES `sample`.`users` (`id`),
  CONSTRAINT `fk_id_file`
    FOREIGN KEY (`id_file`)
    REFERENCES `sample`.`files` (`id`),
  CONSTRAINT `fk_id_u_type`
    FOREIGN KEY (`id_u_type`)
    REFERENCES `sample`.`units_types` (`id`),
  CONSTRAINT `fk_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `sample`.`projects` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tests included into projects to test a unit type';


-- -----------------------------------------------------
-- Table `sample`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`units` ;

CREATE TABLE IF NOT EXISTS `sample`.`units` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Unit name',
  `id_type` INT UNSIGNED NOT NULL COMMENT 'Unit type id',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `id_unit_type_key_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `id_u_type_key`
    FOREIGN KEY (`id_type`)
    REFERENCES `sample`.`units_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Actual units to be tested';


-- -----------------------------------------------------
-- Table `sample`.`test_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`test_tasks` ;

CREATE TABLE IF NOT EXISTS `sample`.`test_tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_test` INT UNSIGNED NOT NULL COMMENT 'Target test',
  `id_unit` INT UNSIGNED NOT NULL COMMENT 'Target unit selected by a type vs a test unit type',
  `id_schedule` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Scheduled test',
  `steps` INT NOT NULL DEFAULT '1' COMMENT 'Number of repetitions',
  `id_tester` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Tester who launched the test or NULL if launched automatically',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_schedule_idx` (`id_schedule` ASC) VISIBLE,
  INDEX `fk_test_key_idx` (`id_test` ASC) VISIBLE,
  INDEX `fk_tester_key_idx` (`id_tester` ASC) VISIBLE,
  INDEX `fk_unit_key_idx` (`id_unit` ASC) VISIBLE,
  CONSTRAINT `fk_schedule`
    FOREIGN KEY (`id_schedule`)
    REFERENCES `sample`.`schedules` (`id`),
  CONSTRAINT `fk_test_key`
    FOREIGN KEY (`id_test`)
    REFERENCES `sample`.`tests` (`id`),
  CONSTRAINT `fk_tester_key`
    FOREIGN KEY (`id_tester`)
    REFERENCES `sample`.`users` (`id`),
  CONSTRAINT `fk_unit_key`
    FOREIGN KEY (`id_unit`)
    REFERENCES `sample`.`units` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tasks for testing unit by a test with repetitions';


-- -----------------------------------------------------
-- Table `sample`.`tasks_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`tasks_results` ;

CREATE TABLE IF NOT EXISTS `sample`.`tasks_results` (
  `task_id` INT UNSIGNED NOT NULL COMMENT 'Task to be run',
  `step` INT NOT NULL COMMENT 'Task step',
  `result` ENUM('PASS', 'FAIL', 'ONGO') NOT NULL COMMENT 'Passed of failed test task step',
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time of the task start',
  `stopped_at` DATETIME NULL DEFAULT NULL COMMENT 'Time of a stop or NULL',
  PRIMARY KEY (`task_id`, `step`),
  CONSTRAINT `fk_task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `sample`.`test_tasks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Results of the tasks execution';

USE `sample` ;

-- -----------------------------------------------------
-- Placeholder table for view `sample`.`categorizedtests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`categorizedtests` (`Project` INT, `Test` INT);

-- -----------------------------------------------------
-- function launch_test_task
-- -----------------------------------------------------

USE `sample`;
DROP function IF EXISTS `sample`.`launch_test_task`;

DELIMITER $$
USE `sample`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `launch_test_task`(task_id INT, step INT) RETURNS int
    DETERMINISTIC
BEGIN
   INSERT INTO tasks_results (tasks_results.task_id, tasks_results.step, tasks_results.result)
	   VALUE (task_id, step, 'ONGO'); 
RETURN 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `sample`.`categorizedtests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample`.`categorizedtests`;
DROP VIEW IF EXISTS `sample`.`categorizedtests` ;
USE `sample`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `sample`.`categorizedtests` (`Project`,`Test`) AS select `pjt`.`name` AS `Project`,`sample`.`tests`.`name` AS `Test` from (`sample`.`tests` join `sample`.`projects` `pjt` on((`sample`.`tests`.`id_project` = `pjt`.`id`)));
USE `sample`;

DELIMITER $$

USE `sample`$$
DROP TRIGGER IF EXISTS `sample`.`tasks_results_AFTER_UPDATE` $$
USE `sample`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `sample`.`tasks_results_AFTER_UPDATE`
AFTER UPDATE ON `sample`.`tasks_results`
FOR EACH ROW
BEGIN
   IF NEW.stopped_at IS NOT NULL THEN
    INSERT INTO notifications (notifications.id_user, notifications.message)
	SELECT id_tester, 'Stopped test' FROM test_tasks WHERE test_tasks.id = NEW.task_id;
  END IF;    
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
